### ISSUE TITLE
Regarding AdBlock Plus

### ISSUE THREAD

**Issue by ghost** [CHEF-KOCH/CKs-FilterList#17]
@CHEF-KOCH Please don't make any new changes to the main filter list(CK's-FilterList.txt).

I'm looking over the list, so hold on till then.

Edit:
So, I looked over and noticed that we will have to drop the support for ABP and the ones that don't support modern modifer and parameters. Or maintain a separate list for ABP, AG and uBo.

Some examples are `$important` , `$badfilter` , `$redirect` (which are only supported by uBo and nano and not even by AdGuard), `CSS selector` filter rules, `$first-party` (not supported by AG too) , `popunder` (not supported by AG even) , `websocket` , etc.

**Comment by The-Commissioner** [comment]
So, I looked over and noticed that we will have to drop the support for ABP and the ones that don't support modern modifer and parameters. Or maintain a separate list for ABP, AG and uBo.

Some examples are `$important` , `$badfilter` , `$redirect` (which are only supported by uBo and nano and not even by AdGuard), `CSS selector` filter rules, `$first-party` (not supported by AG too) , `popunder` (not supported by AG even) , `websocket` , etc.

**Comment by The-Commissioner** [comment]
Don't know why I am not able to create pull request for now.

https://gist.github.com/The-Commissioner/2c70d7b627ac01e8c55e67dad4f5ff2e

This list is optimized.
Redundant and duplicate rules have been removed.
Section sorted in ascending order.
Suggests to remove the [Adblock] header since ABP is not fully supported.
Checksum will need to be regenerated.

**Comment by The-Commissioner** [comment]
Hey
After a long thought, I have decided to leave github now. It's nothing from your side.
So a request from my side, please take ownership back from me for both the repo- this one and no script one.(or tell me how to do it from my side).
Also, if there is anything you need to ask, you can do so now.
Once done with, please leave a comment to proceed further.
Thank you.

**Comment by CHEF-KOCH** [comment]
* https://adblockplus.org/development-builds/new-filter-type-option-for-websockets
* https://adblockplus.org/forum/viewtopic.php?f=4&t=40976
* https://issues.adblockplus.org/ticket/1727 
* Adblock Plus ignores (not incompatible) `##script:contains([...])` rules which is related to [inline script](https://issues.adblockplus.org/ticket/748#comment:9) stuff (which also exists in EasyList) 

So overall you're right and the original tickets on this matter shows that ABP is more inefficient.  



**Edit while I wrote this I saw you commented**
In case you delete your account then I not need to remove you, it's an automatically process. But in case you just abandoned your account I can of course remove you from the projects.

It's really sad to hear you leave, maybe consider to switch to GitLab instead (better privacy policy) I was also thinking to make the switch (well I already said this when GitLab was announced) but GitHub became too powerful.

I'm right now a bit shocked reading this from you, I know what you did for AdGuard and other projects (incl. my own). Well, my Riot/Discord channels or eMail are public, we still could stay in contact if there questions or something. Would be sad to loose every contact!

**Comment by The-Commissioner** [comment]
Ah, they must have added the support later on.
With regards to CSS, do check if they support all syntax like :contains :has-text or others like this.

I'm sorry but you must understand how hurt I must be, I thought for their betterment and instead they think of me as the bad guy. I don't wanna be that guy. 

I asked to remove me as I read that someone can pick this username when I delete my account. Also please do take care that I'm no longer active on any of the forums(MDL,AG,wilders,github-after today) by the name of The-Commissioner or any other user handle. Anyone who does create such an impression is an imposter. 

If you ever switch to gitlab, I might consider joining you but don't shift there because of me only.
