### ISSUE TITLE
Unix vs Windows line endings

### ISSUE THREAD

**Issue by AddaxSoft** [CHEF-KOCH/CKs-FilterList#22]
It seems that there is a problem when download the hosts file in linux based OS
![image](https://user-images.githubusercontent.com/6898938/41591931-694f4caa-73bb-11e8-88d9-0575a2b8c988.png)

**Comment by CHEF-KOCH** [comment]
No information given -> wontfix.

**Comment by AddaxSoft** [comment]
@CHEF-KOCH what more info do you need? This applies to all linux based and a very common problem with line ending character I'm not sure what more info do you need

**Comment by CHEF-KOCH** [comment]
* Which hosts file?
* Which revision?
* Why is it a problem, cause Linux itself usually ignores the line ending (same like Windows) unless it's LF (which is not I use CRLF by default in Visual Studio Code)
* Why is line ending a download problem? ..."_problem when download_" ????

**Comment by AddaxSoft** [comment]
Which hosts file?
this one here: CK's-Spotify-HOSTS-FilterList.txt, but I assume all of them have the same issue

Which revision?
latest @ https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/HOSTS/CK's-Spotify-HOSTS-FilterList.txt

Why is it a problem, cause Linux itself usually ignores the line ending (same like Windows) unless it's LF (which is not I use CRLF by default in Visual Studio Code)
I used curl to download it from raw (I have a cron job doing it for me weekly to update the hosts files)

Why is line ending a download problem? ..."problem when download" ????
see above answer

**Comment by CHEF-KOCH** [comment]
It's still a wontfix because this needs to be configured within curl. [My lists are correct](http://man7.org/linux/man-pages/man5/hosts.5.html) and the line ending is correct.

To remove `||` at the beginning at each new line use something like:
* `curl -s https://your-ad-blocking-list | sed 's/^||//'`

... or to remove everything like `||` and `^` you can use  something like:
* `curl -s https://your-ad-blocking-list | sed 's/^||//' | cut -d'^' -f-1`

There is more than one way to parse the list down and there is no right way, however, some methods are faster.

**Comment by AddaxSoft** [comment]
I'm not sure what does this have to do with `||`, did you mention it as an example?
I've described the problem in more details [here](https://superuser.com/questions/1332670/curl-wget-is-adding-an-extra-m-when-i-append-data-to-a-file)

I'm not sure why is this happening only when I try to append the mentioned host file to another one

**Comment by AddaxSoft** [comment]
Ok here is an update and a quick way to reproduce this:

`echo 123 > hosts && curl -s "https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/HOSTS/CK's-Spotify-HOSTS-FilterList.txt" >> hosts`

this will produce a corrupted endline 

![image](https://user-images.githubusercontent.com/6898938/41622207-2bc1887c-740f-11e8-90e8-a2b8fcb40ed9.png)

downloading the host file directly without appending it to another file doesn't seem to be a problem. I wonder why?

**Comment by AddaxSoft** [comment]
ok I think I got the root cause of the problem.


when *unix system create a file, the end line character is **0x0a** ONLY

```
00000000: 31**0a** 2320 5469 746c 653a 2043 4845 462d  1.# Title: CHEF-
00000010: 4b4f 4348 2773 2053 706f 7469 6679 2041  KOCH's Spotify A
00000020: 642d 4669 6c74 6572 204c 6973 740d 0a23  d-Filter List..#
00000030: 2044 6573 6372 6970 7469 6f6e 3a20 426c   Description: Bl
00000040: 6f63 6b73 2061 6c6c 2061 6e6e 6f79 696e  ocks all annoyin
00000050: 6720 5370 6f74 6966 7920 4164 732e 0d0a  g Spotify Ads...
```

but your host file line ends with 0x0d 0x0a, which confuses the file parser.I think a tool line dos2unix should solve this issue. 

```
00000000: 2320 5469 746c 653a 2043 4845 462d 4b4f  # Title: CHEF-KO
00000010: 4348 2773 2053 706f 7469 6679 2041 642d  CH's Spotify Ad-
00000020: 4669 6c74 6572 204c 6973 740d 0a23 2044  Filter List..# D
00000030: 6573 6372 6970 7469 6f6e 3a20 426c 6f63  escription: Bloc
00000040: 6b73 2061 6c6c 2061 6e6e 6f79 696e 6720  ks all annoying
00000050: 5370 6f74 6966 7920 4164 732e **0d0a** 2320  Spotify Ads...#
```

**Comment by CHEF-KOCH** [comment]
Thanks finally something which I really can work with. 

I in the meantime asked in PI-Hole project if there is a way to do/check this via curl directly since I'm not really an advance curl user (I only download something with it and that's it [like most Pi-Hole users]).

I'm not really sure if I like to switch from \r\n (0x0D 0x0A) to \n (0x0A) in Visual Studio Code since this would affect all my text files in general, I still would prefer that curl or wget would take care of this and correct it if necessary. I did some tests with curl yesterday because it has the ability to use the --crlf command line but that doesn't solve the problem. 

* https://superuser.com/questions/1332670/curl-wget-is-adding-an-extra-m-when-i-append-data-to-a-file/1332983#1332983

**Comment by AddaxSoft** [comment]
@CHEF-KOCH I was about to share that superuser answer, I think the problem is not this host file but the other one :) .. for now a quick and dirty fix is using dos2unix on `/etc/hosts` after merging the two.
