### ISSUE TITLE
[Enhancement]uMatrix filter list

### ISSUE THREAD

**Issue by The-Commissioner** [CHEF-KOCH/CKs-FilterList#3]
Hi, I made some changes to the [umatrix file](https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/CK's-uMatrix-FilterList.txt).

1. Duplicate entries have been removed.
2. Entries are organized alphabetically/ascending order.
3. Checksum is not added(doesn't correspond to the file). If needed, please add it manually.

https://gist.githubusercontent.com/The-Commissioner/617a6365c9b2bae07bb1c3129f918d0c/raw/5398a0d81b36e44591dc34cc955de615a7bcfe47/gistfile1.txt

**Comment by CHEF-KOCH** [comment]
Many thanks, I just added you under the new created Credits section.

I merge it as soon I get the uBo list cleaned up.

**Comment by The-Commissioner** [comment]
The way uBo list has been designed now, it's almost impossible to arrange it in an order, remove duplicates and still maintain the segregation that you are using.
The uBo list IMO needs a review.

**Comment by CHEF-KOCH** [comment]
Thanks it's on the todo now, I already  started to seperate the lists cause it's too much otherwise. Most extensions or tools which are filter it already getting a race condition, so I'm forced to keep the lists '_small_'  (as much as possible). 

About uBO, indeed, it's work-in-process now. I hope I get it back this weekend.

**Comment by The-Commissioner** [comment]
I would like to suggest something here. I would advise you to make a folder here with invidual lists - so it's esy for you to segregate and maintain and at the top a single file with everything included, that ways it is possible to have the easiness that you demand to maintain the list and the easiness to maintain the overall list.
Moreover, it gives choice to user, if they want the full list or only some parts.

**Comment by CHEF-KOCH** [comment]
Sure you can say anything you like here.

I will definitly split uBO list in seperate ones it's simply better to maintain. Umatrix list (for now stays) and might gets replaced with IP/ASN rules so you can easily block Facebook and don't need thousends of lines of domains. I'm currently working with someone together to make a pull request for Nano Adblocker so it might block in the future ASN based rules. The domains which are malware based will stay at it is currently until I found something more efficent to block it. 

I need to re-think to maintain several list without integrating lots of redundant rules.

**Comment by The-Commissioner** [comment]
Yes this is good now.
The main CK-Filter list is the one that should be accumulated with all the the other folders(lists contained in them). And this is the list that should be made available/advertised to be used by users on the readme page. 
The folders that you have created should be the list that you(personally) should be using for testing purposes and if anything requires a change, fix it in individual file rather than the main file (CK-filterlist). And then after assuring everything is right, the main list can be updated on a monthly basis or twice a month. I see you will create a /ubo folder as well, there you can again segregate files already in the list into different folders like generic element hiding, third-party, or trackers,etc. - the categories you have mentioned in the main filter list file.

Now the main list would no longer require segregation and can be used to identify duplicates, sorted in ascending order.

It may seem a lot of work now, but this is just one time process, and afterwards it will be smooth sailing for the users as well as you to maintain it.

**Comment by CHEF-KOCH** [comment]
So let me retroperspective this before I change it.

You basically say that:
* CK's-FilterList.txt should get everything? Incl. the lists from the folders? Holy moly!
* The ones in the folders are for testing and if okay it should be merged with the main list CK's-FilterList.txt, right?
* The CK's-FilterList.txt gets only updated (merged) once a month  (or more - depending) when everything is 'correctly' adopted from the other lists, right?

Shit man, that's an assload of work, but hm I need to check this.

**Comment by The-Commissioner** [comment]
Yeah that's somewhat the idea. 
But it's your repository, you have the fnal say.
If anything needed from my side, do tell.

**Comment by CHEF-KOCH** [comment]
I'll try to keep up your suggestions, however some things will remain _optional_. Since I provide anti-Google lists. I simply can't add them into the 'main' list because I _need_ and use Google. So, some lists will be optional (opt-in sub) but will also mentioned in  the Readme.md.

The ongoing work right now will be:
* I start a wiki to explain some things, how to sort lines, remove dubs etc. 
* Update and finalize the Readme.md v1.0 to explain and link everything. Ultimatively the main goal needs to be mentioned I like to mention here that the main goal is (or should) to get rid of lots of 'smaller' lists so that you only have to subscribe to Easylist + my list. I'll not compete against EasyList so I don't even try. 
* Bug reports and the wiki will be connected to 'explain' guidelines to contribute to the project. 
* I'll add you as Collaborator so you can fix/submit something without asking me or doing a PR. I trust you on this, it's up to you if you 'accept' the request or not.

I think that's a lot for now. I only can start the 'real' work until all of this is done. Because there must be clear guidance and goals defined.

**Comment by The-Commissioner** [comment]
I have made some changes as you will notice. For things I was sure, I merged it directly to master branch. For things, I was not sure whether you would have liked those changes or not I have pulled a request.
