### ISSUE TITLE
Is there any reason to block localhost?

### ISSUE THREAD

**Issue by Retia-Adolf** [CHEF-KOCH/CKs-FilterList#33]
![image](https://user-images.githubusercontent.com/34053927/44760710-11b88f80-ab0e-11e8-8a31-a95b76274da4.png)

It's incomprehensible.

**Comment by CHEF-KOCH** [comment]
Localhost and 127.0.0.1 are not the same when it comes to 'firewalling'. E.g. corporate firewall can't block 127.0.0.1. Only a local computer firewall can, at least I've never seen one that does by default. 127.0.0.1 is a special IP, it's a loopback to your own TCP/IP stack. However, in this case, 127.0.0.1 is 'blocked' here in order to prevent attacks which might monitor your router login etc. coming from e.g. extension or re-directions.
