### ISSUE TITLE
Android Filter List as plain HOSTS file?

### ISSUE THREAD

**Issue by dimqua** [CHEF-KOCH/CKs-FilterList#35]
Can you please create a HOSTS version of your Android Filter List?

**Comment by CHEF-KOCH** [comment]
I'll consider it.

**Comment by CHEF-KOCH** [comment]
I decided against it because:
* Android plain HOSTS blocking is a pain in the ass, it is ineffective and drains the battery instead of blocking thousands of domains google.ads.com you simply can work with regular expressions like *ads.* which saves space and memory.
* HTTPS ads might be bypassed anyway because this requires a VPN interface to solve to monitor them -> more battery drain.
* There better tools out there to block ads which cover the mentioned problems like Blockada and AdGuard or AdAway. The benefit is also that you get automatic updates + you can log / see DNS queries in order to help this and other projects. 
* You can manually do this I write some instructions in the Wiki.

**Comment by dimqua** [comment]
I respect your decision, but your answer confused me, tbh.

> you simply can work with regular expressions

By using what? Most of the DNS-based adblockers (including Blokada and Adguard) for Android require a VPN interface to function, which leads to significant battery drain, at least, in my experience.

> like Blockada and AdGuard or AdAway

But AdAway uses HOSTS.

>You can manually convert the existent list

Yes, this is what I do right now. :-)

**Comment by CHEF-KOCH** [comment]
Some DNS provider like OpenDNS (Family filter + requires registered account) allow you to use or add their own list, the benefit here is that no app is required. Some of them allowing you to work with regular expressions but there are only a handful. 

## OT
I'm working with someone together in order to bring Unbound into Android (such an alpha app already exists but I need more time to finish it I also suffer from financial problems right now to finish several projects). 

## Android Ad-blocking
On Android, I see adblocking as a special case because you can use FOSS apps (there really alternatives out there for almost every case) and some browsers are coming with their own or the well-known lists which is in my opinion enough. 

<details>
 <summary>Adblocking warning!</summary>
I also want to mention right here and right now that blocking ads or entire domains do not improve any security aspect. I say this as clear as possible here because I have the feeling (due to wrong marketing) people think it helps but this is not entirely correct since an attacker could check the current filter list or create an entirely new domain to bypass such filters, in other words, I see it like the Tor project, this requires huge maintenance and is depending on the currently integrated domains which is not necessarily a security benefit, which is the reason why Tor browser not adopted/integrated adblocking via addon.

https://www.torproject.org/projects/torbrowser/design/
</details>

**Comment by dimqua** [comment]
Thanks for the info!

> I'm working with someone together in order to bring Unbound into Android

What is the purpose? AFAIK, unbound does not support regex rules for adblocking, but dnscrypt-proxy does (and already exists for Android).

> some browsers are coming with their own or the well-known lists

On other hand, the only browser that currently has full-featured adblock solutions (such as uBlock Origin and Adguard) is Firefox and derivatives.

**Comment by CHEF-KOCH** [comment]
[Unbound also supports regex](https://github.com/cbuijs/unbound-dns-firewall/blob/master/regex-blacklist), you can load scripts which executes several patterns before applying to DNS requests.  DNSCrypt is like Unbound not really designed to do this it's optional but Unbound has several benefits.
