### ISSUE TITLE
[Spotify] Web-Player buttons aren't working

### ISSUE THREAD

**Issue by SURE-E** [CHEF-KOCH/CKs-FilterList#36]
**Describe the site issue**
When applying `CHEF-KOCH's Spotify Ad-Filter List` to uBlock Origin filter, all music stops playing. 

### Test link
https://open.spotify.com/collection/tracks

### Screenshot of the developer console (**if possible**)
![image](https://user-images.githubusercontent.com/17045972/45221004-199ad100-b27e-11e8-95c0-5065134352d0.png)
![image](https://user-images.githubusercontent.com/17045972/45221043-38996300-b27e-11e8-9951-d0c301d4896c.png)
![image](https://user-images.githubusercontent.com/17045972/45221710-451ebb00-b280-11e8-8b50-719f498b1695.png)

### Reproduction steps
1.  Login into Spotify in Chrome w/ uBlock Origin installed
1.  Play music to confirm functioning sound
1.  While music is playing, open uBlock Origin settings
1.  Click `Filter Lists`
1.  Scroll to `Custom`
1.  Select `Import` checkbox
1.  Enter `CHEF-KOCH's Spotify Ad-Filter List` URL into `Import` textbox
1.  Click `APPLY CHANGES`
1.  Wait (approx 10 or so seconds for the filter to apply)

#### Actual Result
1. Music playing
1. All web player buttons (play, forward, backward) no longer function

#### Expected Result
1. Music continues to play
1. All buttons function

### Environment specifications
- Filter list version:  `! Version: 0.0.0.7`
- Operating system and version: Windows 10 
![image](https://user-images.githubusercontent.com/17045972/45221785-8747fc80-b280-11e8-8ee9-a968ef05cf14.png)
- Browser and version: Version 68.0.3440.106 (Official Build) (64-bit)
- Adblocker and version:  uBlock Origin v1.16.18

**Comment by CHEF-KOCH** [comment]
The issue is invalid since you need to login into the page in order to see any of the tracks, once you're login into Spotify website it changes the tracks/player/javascript according to your account selected country/IP/preferences.

However, I can reproduce a common problem with the web-player (thanks to your debug console output) I'm not sure if there is a quick fix for that since top-level domains like facebook, Spotify & co changing their javascript on a daily basis. If you remove the last entries within the list (website specific) everything goes back to normal, but this causes the desktop clients to trigger ads once you skip certain songs for x times - so I can't remove it right now until I decided if I fully drop support or continue it and investigate into every javascript change they made (it's a lot of work).
