### ISSUE TITLE
Snappa Background Images aren't applied

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/CKs-FilterList#63]
**Describe the site issue**
The CHEF-KOCH's Random third-party Filter List is blocking the background apply in the graphic generator.

### Test link
https://snappa.com/

### Screenshot of the web page (_optional_)
![capture](https://user-images.githubusercontent.com/16375271/50741805-64abfd00-11fa-11e9-9c18-fb7fb30ce939.PNG)

### Screenshot of the developer console (**if possible**)
-

### Reproduction steps
1. Go to https://snappa.com/
2. Create account/Log In (whoops.. :disappointed: )
3. In https://snappa.com/app (Create a Graphic) select any size and press Create From Scratch...
4. At the Graphic Generator, select Bkgrnd and press Photos (not pattern/colors)
5. Select any image and check the load loop.

### Environment specifications

Filter list version: 0.0.0.01
Operating system and version: Windows 7 x64 SP1 (latest updates)
Browser and version: Chrome Beta 72
Adblocker and version: uBlock 1.17.4

### Add any other additional helpful information (_optional_)
I've disabled the filters one by one to figure out which one is problematic, because of the site structure (menus without refresh of the page) I couldn't get the uBlock logger to show me the blocked content and the filters which did the block...

**Comment by ArmynC** [comment]
It's still happening to me... I found exactly what was causing it:
![capture1](https://user-images.githubusercontent.com/16375271/50766443-21d93c00-1271-11e9-8909-02dcfc7a3404.PNG)

Static filter `/\.com\/.*[0-9]{2,7}\//$third-party,xmlhttprequest` found in:
CHEF-KOCH's Random third-party Filter List

**Comment by CHEF-KOCH** [comment]
Then don't use the random list?!

**Comment by ArmynC** [comment]
Yeah :smile:, I can remove it but in many cases it would help me and in the same time I wanted to report "for posterity". And for a possible fix for multiple cases (scripts) [if there are more of them]?

**Comment by CHEF-KOCH** [comment]
Your reports (I know you mean well) are not (always) helpful because it costs time to debug the problem, it would be better to directly create a pull request with a screenshot of the developer console and uBO console. This would help to reproduce it and see if it's a Browser/Website or filter problem. Sometimes it's also an extension problem (bug).

You're above screenshot was helpful (in this case!) but random is random and there is no other possibility to block randomly generated ads (since no one found a way to deal better with it except with wildcards) - the only thing I can think of is that I exclude the website's which then going into the unbreak filter list however I don't really like to do this since this costs much a lot of time (and in the meantime the website might have already changed their ads system or ads logic).
